### ISSUE TITLE
Client handshake returns error message "Transport unknown"

### ISSUE THREAD

**Issue by Maxwell2022** [socketio/socket.io#1577]
I was trying to initialize a handshake, following the specs I've found at [LearnBoost/socket.io-spec](https://github.com/LearnBoost/socket.io-spec#handshake). Sometime I found that it has to be done with a `POST` request, sometime with `GET`. I've tried both of them and they both returned the same error:

``` bash
GET http://acme.local:3700/socket.io/1
or
POST http://acme.local:3700/socket.io/1
```

> {
>     "code": 0,
>     "message": "Transport unknown"
> }

**Comment by Kernelzero** [comment]
+ same error

**Comment by steviesama** [comment]
I actually got through the first 2 completing the handshake, and the on connection emit actually fires and I pick it up in the serial monitor of my Arduino, but the third connection upgrade request I get bad request. So frustrating.

**Comment by Narasimha-Murthy** [comment]
when  i  try open socket  my getting error message is 
2016-03-25 17:47:36.043 szx[3499:103945] ERROR: handshake failed ... The request timed out.

**Comment by altanai** [comment]
since im also facing this , i guess its not fixed uptill now . im using "socket.io": "^1.4.5",

**Comment by rosarionakkocom** [comment]
For Those still looking for an answer for here:

https://www.npmjs.com/package/passport.socketio

**Comment by kevinguard** [comment]
@rosarionakkocom That didn't help.

**Comment by drekka** [comment]
Just hit this as well. Trying various options. Am just lying to test out a server I've built and using PAW as a client.

**Comment by afshinm** [comment]
I fixed this problem by adding this setting to my socket.io server:

```
var socket = io({
  transports: [
    'websocket', 
    'flashsocket', 
    'htmlfile', 
    'xhr-polling', 
    'jsonp-polling', 
    'polling'
  ]
});
```

read more here: http://stackoverflow.com/a/24244413/375966

**Comment by darrachequesne** [comment]
@afshinm please note that, as documented [there](https://github.com/socketio/socket.io/blob/master/docs/API.md#new-serverhttpserver-options), the order in `transports` options is important:

> Note: The order is important. By default, a long-polling connection is established first, and then upgraded to WebSocket if possible. Using ['websocket'] means there will be no fallback if a WebSocket connection cannot be opened.

**Comment by pathbox** [comment]
@afshinm Thanks,  it works

**Comment by darrachequesne** [comment]
Please note that since socket.io version 1.x, the only valid values for `transports` are:
- websocket
- polling

All the other values in @afshinm 's answer won't be used (in fact, only websocket transport will be used in that case).

**Comment by Jor2611** [comment]
I still cant load my page. it brings
```
 {
code: 0,
message: "Transport unknown"
}
```
My domain under cloudflare with its ssl. My app running on ec2 instance application work with public ip and instance name but it working with http.I need to run that app with https and with my domain.
So here is my backend side code.
   ```
const express = require('express');
const app = express();

const fs = require('fs');
const path = require('path');
const cors = require("cors");

app.use(express.static(path.join(__dirname,"public")));
app.use(cors());

let cert = fs.readFileSync(path.join(__dirname,"/mycert.pem"));
let key = fs.readFileSync(path.join(__dirname,"/mykey.key"));
let credentials = {cert,key};

const httpsServer = require("https").Server(credentials,app);
const io = require('socket.io')(httpsServer,{path:'/game', transports: [
    'websocket',
    'flashsocket',
    'htmlfile',
    'xhr-polling',
    'jsonp-polling',
    'polling'
  ]});
httpsServer.listen(2096, function() {
    console.log('listening on *2096');
});

io.on('connection', function(socket) {
    let balance=6000;

    console.log('a user connected');
    let count = 0;

    socket.on('giveValue', function(data) {
        // console.log(count);
        count++;
        if (data.msg === "New Value" && count<=100) {


          let x = Math.floor(Math.random() * 100 - 50);
            balance += x;
         
                socket.emit('takeValue', { balance: balance, value: x });
            });
        }
    });

    socket.on('disconnect', function() {
        console.log('User disconnected');
    });

    socket.on('getBalance', (data) => {
        if (data.msg === 'bringBalance') {
            socket.emit('ubalance', { data: balance });
        }
    })

});
``
This is my angular 6 code (which is built in public directory of server) .
```
this.socket = io.connect('/', {
      secure: true,
      requestCert: true,
      rejectUnauthorized: false,
      transports: [
        'websocket', 
        'flashsocket', 
        'htmlfile', 
        'xhr-polling', 
        'jsonp-polling', 
        'polling'
      ]
    });
```
And my nginx config.
```
location /game/ {
               alias /home/ubuntu/server2/public;
                proxy_pass https://localhost:2096;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
        }
```
And this is what i get 
![capture](https://user-images.githubusercontent.com/26968044/48185478-8732ae80-e34e-11e8-9d42-fdac1d946d9d.PNG)

**Comment by TungstenVn** [comment]
> Closing this in favor of [socketio/socket.io-protocol#10](https://github.com/socketio/socket.io-protocol/issues/10).
> 
> If this issue occurs when using socket.io (not a custom implementation) what @coulix said is likely the fix: make sure that the client and server are of the same version. Please do open another issue about it if this doesn't help. :)

it works !!!, my client side is using a lib call elephant.io, and it is using verison of 1.0.0, but my socket.io is using 4.0.0, so i install the socket version 1.0.6 (as i see in the terminal) and the problem is fixed even though i dont know why
