### ISSUE TITLE
After upgrading to Websocket transport, Socket.io still uses polling transport

### ISSUE THREAD

**Issue by phtdce** [socketio/socket.io#2720]
After upgrading to Websocket transport succesfully, Socket.io still uses polling to send and receive messages. It's a bug, isn't it ? How could i use Websocket to send and receive messages ? 
I use Node.js version 4.5.0 and Socket.io version 1.5.0.
![untitled](https://cloud.githubusercontent.com/assets/4677125/19407562/2eebc656-92d0-11e6-9f5b-638b99d82ca1.jpg)

**Comment by carpii** [comment]
socket.io used to try and establish a websocket transport, and then fall back to polling or Flash etc.
This has changed though, I think as of socket.io 1.x

Now clients start by a polling request, and then upgrades to websocket if and when they can. 

You can restrict it to websocket transport only (but must be done in the client AND the server).
I use this in a project I have deployed in the past week, although I'm not yet 100% convinced it's a great idea... 

You may find this useful... http://stackoverflow.com/questions/28238628/socket-io-1-x-use-websockets-only

**Comment by phtdce** [comment]
I have tried the tutorial from stackoverflow but it's still not working
